name: Node.js CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: docker2297/node-api-github-actions-azure

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build & Publish to ACR
        uses: azure/docker-login@v1
        with:
          login-server: billingreviewacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t billingreviewacr.azurecr.io/node-api-github-actions-azure:${{ github.sha }}
          docker push billingreviewacr.azurecr.io/node-api-github-actions-azure:${{ github.sha }}